Vagrant.configure(2) do |config|
  config.vm.box = 'centos/7'

  config.vm.provider 'vmware_fusion' do |v|
    v.vmx['memsize'] = 4096
    v.vmx['numvcpus'] = 2
  end

  config.vm.provider 'vmware_workstation' do |v|
    v.vmx['memsize'] = 4096
    v.vmx['numvcpus'] = 2
  end

  config.vm.provider 'parallels' do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.provider 'virtualbox' do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    # ansible.become = true
    ansible.compatibility_mode = '2.0'
    ansible.playbook = "./add_sshkey.yaml"
  end

  # config.vm.network 'forwarded_port', guest: 8080, host: 8080
  # config.vm.network 'forwarded_port', guest: 80, host: 8888
end